/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiActivity: typeof import('~icons/bi/activity')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
