/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardsAndCertificationForm: typeof import('./src/components/resume/AwardsAndCertificationForm.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavText: typeof import('bootstrap-vue-next')['BNavText']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    DesiredJob: typeof import('./src/components/resume/DesiredJob.vue')['default']
    DesiredJobList: typeof import('./src/components/resume/DesiredJobList.vue')['default']
    DesiredJobListItem: typeof import('./src/components/resume/DesiredJobListItem.vue')['default']
    EducationForm: typeof import('./src/components/resume/EducationForm.vue')['default']
    GithubRepository: typeof import('./src/components/resume/GithubRepository.vue')['default']
    MainNavHeader: typeof import('./src/components/common/MainNavHeader.vue')['default']
    MainTechnologies: typeof import('./src/components/resume/MainTechnologies.vue')['default']
    Profile: typeof import('./src/components/resume/Profile.vue')['default']
    ResumeDetailHeader: typeof import('./src/components/resume/ResumeDetailHeader.vue')['default']
    ResumeFormLayout: typeof import('./src/components/layout/resume/ResumeFormLayout.vue')['default']
    ResumeList: typeof import('./src/components/resume/ResumeList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechnologyList: typeof import('./src/components/resume/TechnologyList.vue')['default']
    TechnologyListItem: typeof import('./src/components/resume/TechnologyListItem.vue')['default']
    WorkExperienceForm: typeof import('./src/components/resume/WorkExperienceForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
